# Generated by Django 5.2.7 on 2025-10-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocion',
            name='descuento',
        ),
        migrations.AddField(
            model_name='promocion',
            name='activa',
            field=models.BooleanField(default=True, help_text='Marcar para que la promoción esté disponible.'),
        ),
        migrations.AddField(
            model_name='promocion',
            name='tipo',
            field=models.CharField(choices=[('PORCENTAJE', 'Porcentaje (%)'), ('VALOR_FIJO', 'Valor Fijo ($)'), ('2X1', '2x1 (Llevar 2, Pagar 1)')], default='PORCENTAJE', help_text='Tipo de descuento aplicado.', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promocion',
            name='valor_descuento',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='El valor del descuento (ej: 10 para 10% o 5000 para $5000)', max_digits=10, null=True),
        ),
    ]
